# Generated by Django 4.2.4 on 2023-08-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_product_product_category_alter_product_product_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
