# Generated by Django 4.2.4 on 2023-08-15 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Product_statuc',
            new_name='payment_status',
        ),
    ]
