# Generated by Django 4.2.4 on 2023-08-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_product_statuc_cart_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Kids', 'kids'), ('Accessories', 'Accessories'), ('Shoes', 'Shoes'), ('Goggles', 'Goggles'), ('Makeup', 'Makeup'), ('Furniture', 'Sandals'), ('Party Bulb', 'Party Bulb'), ('Kitchen tools', 'Kitchen tools')], max_length=100),
        ),
    ]
