from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('shop/',views.shop,name='shop'),
    path('detail/',views.detail,name='detail'),
    path('contact/',views.contact,name='contact'),
    path('checkout/',views.checkout,name='checkout'),
    path('signup/',views.signup,name='signup'),
    path('login/',views.login,name='login'),
    path('logout/',views.logout,name='logout'),
    path('change-password/',views.change_password,name='change-password'),
    path('forgot-Password/',views.forgot_password,name='forgot-Password'),
    path('verify-otp/',views.verify_otp,name='verify-otp'),
    path('new-password/',views.new_password,name='new-password'),
    path('profile/',views.profile,name='profile'),

    path('seller-index/',views.seller_index,name='seller-index'),
    path('seller-add-product/',views.seller_add_product,name='seller-add-product'),
    path('seller-view-product/',views.seller_view_product,name='seller-view-product'),
    path('seller-view-order/',views.seller_view_order,name='seller-view-order'),
    path('seller-view-detail/<int:pk>/',views.seller_view_detail,name='seller-view-detail'),
    path('seller-edit-product/<int:pk>/',views.seller_edit_product,name='seller-edit-product'),
    path('seller-delete-product/<int:pk>/',views.seller_delete_product,name='seller-delete-product'),
    path('view-detail/<int:pk>/',views.view_detail,name='view-detail'),
    path('add-to-wishlist/<int:pk>/',views.add_to_wishlist,name='add-to-wishlist'),
    path('wishlist/',views.wishlist,name='wishlist'),
    path('remove-from-wishlist/<int:pk>/',views.remove_from_wishlist,name='remove-from-wishlist'),
    path('add-to-cart/<int:pk>/',views.add_to_cart,name='add-to-cart'),
    path('cart/',views.cart,name='cart'),
    path('remove-from-cart/<int:pk>/',views.remove_from_cart,name='remove-from-cart'),
    path('change-qty/',views.change_qty,name='change-qty'),
    path('create-checkout-session/',views.create_checkout_session,name='create-checkout-session'),
    path('success.html/', views.success,name='success'),
    path('cancel.html/', views.cancel,name='cancel'),
    path('myorder/',views.myorder,name='myorder'),
    path('ajax/validate-email/',views.validate_signup,name='ajax/validate-email'),
    path('ajax/validate-email/',views.validate_login,name='ajax/validate-email'),
    path('ajax/validate-email/',views.validate_cp,name='ajax/validate-email'),
    
    path('women/',views.women,name='women'),
    path('men/',views.men,name='men'),
    path('kids/',views.kids,name='kids'),
    path('accesseries/',views.accesseries,name='accesseries'),
    path('shoes/',views.shoes,name='shoes'),
    path('Goggles/',views.Goggles,name='Goggles'),
    path('Makeup/',views.Makeup,name='Makeup'),
    path('Party-Bulb/',views.Party_Bulb,name='Party Bulb'),
    path('Furniture/',views.Furniture,name='Furniture'),
    path('Kitchen-tools/',views.Kitchen_tools,name='Kitchen tools'),


    path('sync_products_to_shopify/',views.Sync_products_to_shopify,name='sync_products_to_shopify'),
    path('get_shopify_product/',views.get_shopify_product,name='get_shopify_product'),
    path('update_shopify_product_data/<int:product_id>/',views.update_shopify_product_data,name='update_shopify_product_data'),
    path('delete_shopify_product/<int:product_id>/',views.delete_shopify_product,name='delete_shopify_product'),
    path('create_order_in_shopify/',views.create_order_in_shopify,name='create_order_in_shopify'),

]
